language: python
python:
  - '2.7'
services: docker
sudo: required
env:
  global:
  - ESPA_PROC_ENV=dev
  - ESPA_PROC_CONFIG_PATH=${TRAVIS_BUILD_DIR}/run/config.ini
install:
- pip install --process-dependency-links -e .
- pip install -e .[test]
- pip install codecov
script:
- "pytest --cov=./"
#    pylint --rcfile=.pylintrc api -f parseable -r n && \
#    mypy --silent-imports api && \
#    pycodestyle api --max-line-length=120 && \
#    pydocstyle api
after_success:
- codecov
- docker-compose -f test/docker-compose.yaml down
deploy:
  - provider: script
    script: make docker-deploy
    on:
      branch:
        - master
        - develop
        - docker-devel
notifications:
  email:
    on_success: never
    on_failure: change

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - docker-compose -f test/docker-compose.yaml up -d
  - NGINX_IP=`docker inspect -f "{{ .NetworkSettings.Networks.test_espa_processing.IPAddress }}" test_nginx_1`
  - NGINX_URL="http://$NGINX_IP"
  - NGINX_DATA="test/nginx/data"
cache:
  bundler: true
  directories:
    - $HOME/docker
